---
- hosts: all
  gather_facts: False
  tasks:

  - name: Set Permissions and Attributes to the GRUB file
    file:
      path: /boot/efi/EFI/redhat/grub.cfg
#      path: /etc/grub2.cfg
      mode: 700
#      attr: '+i'
    register: output  
  
  - name: Print a debug message
    debug:
      msg: "{{ output }}"
