---
- hosts: all
  gather_facts: False
  tasks:

  - name: Find binaries with suid/sgid set
    shell: find /tmp -xdev \( -perm -4000 -o -perm -2000 \) -type f ! -path '/proc/*' -print 2>/dev/null
    register: sbit_binaries
    changed_when: false

  - name: Remove suid/sgid bit from all binaries
    file:
      path: '{{ item }}'
      mode: 'a-s'
      state: 'file'
      follow: 'yes'
    with_items: " {{ sbit_binaries.stdout_lines }} "
